### ISSUE TITLE
请问如何修改set-config!呢？

### ISSUE THREAD

**Issue by findmyway** [killme2008/clj.qiniu#2]
您好，由于海外服务器上传几乎总是失败，在网上查到需要将上传地址改为up.qiniug.com，我看了下源码发现需要在set-config!里修改

不知道可否通过传参 的形式修改呢？

最近刚学clojure，很多页不是太懂，我想着可能需要改下源码然后重新打包？

**Comment by findmyway** [comment]
我通过import Config直接用set!修改了...

**Comment by killme2008** [comment]
发布了 0.1.2，set-config! 支持 `up-host` 参数。
